name: .NET Core

on:
  push:
    branches: [ master, release-1.1 ]
  pull_request:
    branches: [ master, release-1.1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test HelloWorldTest 
    - name: Add package StyleCop.Analyzers
      run: dotnet  add HelloWorldSolution package StyleCop.Analyzers
    - name: Building again for linting 
      run: dotnet build
    - name: Running integration Test
      if: github.ref == 'refs/heads/master'
      run: dotnet test HelloWorldSolutions.Tests

