name: .NET Core

on:
  push:
    branches: [ master, release* ]
  pull_request:
    branches: [ master, release* ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ci_node_index: [0, 1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      env: 
        ci_node_index: ${{ci_node_index}}      
      run: dotnet test HelloWorldTest 
    - name: Linting Stage
      run: | 
        dotnet  add HelloWorldSolution package StyleCop.Analyzers
        dotnet build
    - name: Running integration Test
      env: 
        ci_node_index: ${{ci_node_index}}
      if: github.ref == 'refs/heads/master'
      run: dotnet test HelloWorldSolutions.Tests


